# Generated by Django 5.0 on 2023-12-19 10:06

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('license', models.CharField(max_length=20)),
                ('manufacture_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1))])),
                ('plate_number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^(IT|GR|RNP|RDF|R[A-H]{2})\\d{3}$', message='Plate number must match the pattern: (IT|GR|RNP|RDF|R[A-H]{2})\\d{3}')])),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('mid_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator('@ur\\.ac\\.rw$')])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+\\d{250,}$')])),
                ('date_of_birth', models.DateField()),
                ('reference_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(99), django.core.validators.MaxValueValidator(999)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valide.vehicle')),
            ],
        ),
    ]
