# Generated by Django 5.0 on 2023-12-19 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valide', '0002_alter_participant_phone_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(help_text='example@ur.ac.rw', max_length=254, validators=[django.core.validators.RegexValidator('@ur\\.ac\\.rw$')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(help_text='+2507821111111', max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number starting with +250 and up to 9 digits.', regex='^\\+250\\d{1,9}$')]),
        ),
    ]
