# Generated by Django 5.0 on 2023-12-19 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valide', '0003_alter_participant_email_alter_participant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('@ur\\.ac\\.rw$')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number starting with +250 and followed by  9 digits.', regex='^\\+250\\d{1,9}$')]),
        ),
    ]
