# Generated by Django 5.0 on 2023-12-19 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valide', '0004_alter_participant_email_alter_participant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid plate number.', regex='^RA[A-H]{1}\\d{3}[A-Z]$|^(RNP|RDF)\\d{3}[A-Z]$|^(IT|GR|GP|\\w{1,6})$')]),
        ),
    ]
